name: Quality Checks

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Validate Maven Project
      run: |
        mvn validate
        echo "Maven project validation completed"
    
    - name: Check Maven Dependencies
      run: |
        mvn dependency:analyze
        echo "Dependency analysis completed"
    
    - name: Verify Project Structure
      run: |
        # Check if required files exist
        if [ ! -f "pom.xml" ]; then
          echo "pom.xml not found"
          exit 1
        fi
        if [ ! -f "assembly.xml" ]; then
          echo "assembly.xml not found"
          exit 1
        fi
        if [ ! -f "docker-compose.yml" ]; then
          echo "docker-compose.yml not found"
          exit 1
        fi
        if [ ! -f "setup-dev.sh" ]; then
          echo "setup-dev.sh not found"
          exit 1
        fi
        if [ ! -f "deploy.sh" ]; then
          echo "deploy.sh not found"
          exit 1
        fi
        echo "Project structure validation completed"
    
    - name: Check for Large Files
      run: |
        # Check for files larger than 50MB (excluding target directory)
        find . -type f -size +50M -not -path "./target/*" -not -path "./.git/*" | while read file; do
          echo "Warning: Large file found: $file"
        done
        echo "Large file check completed"

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Check for Vulnerable Dependencies
      run: |
        mvn org.owasp:dependency-check-maven:check
        echo "OWASP dependency check completed"
    
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-check-report
        path: target/dependency-check-report.html
        retention-days: 7

  build-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Clean Build
      run: |
        mvn clean
        echo "Clean build completed"
    
    - name: Build Distribution
      run: |
        mvn package
        echo "Distribution build completed"
    
    - name: Verify Distribution Contents
      run: |
        cd target
        tar -tzf odoo-openelis-connector-1.0.0-SNAPSHOT.tar.gz | head -20
        echo "Distribution contents verified"
    
    - name: Test Distribution Extraction
      run: |
        cd target
        tar -xzf odoo-openelis-connector-1.0.0-SNAPSHOT.tar.gz
        cd odoo-openelis-connector-1.0.0-SNAPSHOT
        ls -la
        echo "Distribution extraction test completed"
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          target/odoo-openelis-connector-1.0.0-SNAPSHOT.tar.gz
          target/odoo-openelis-connector-1.0.0-SNAPSHOT.zip
        retention-days: 7
